<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ssh_server_allow_passwords'] = 'Разрешить пароли';
$lang['ssh_server_allow_root_login'] = 'Разрешить логин Root';
$lang['ssh_server_app_description'] = 'Приложение SSH Сервер предоставляет для вашей системы инструменты управления политикой безопасности оболочки.';
$lang['ssh_server_app_name'] = 'SSH Сервер';
$lang['ssh_server_app_tooltip'] = 'Изменение настроек безопасности сервера SSH может использоваться для достижения соответствия нормативным требованиям (например, PCI) или применять политику компании по стандартам безопасности.';
$lang['ssh_server_password_authentication_policy_invalid'] = 'Политика аутентификации паролей недействительна.';
$lang['ssh_server_permit_root_login_policy_invalid'] = 'Политика логина root недействительна.';
