#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-ssh-server-core - enabling SSH server"
chkconfig sshd on

logger -p local6.notice -t installer "app-ssh-server-core - starting SSH server"
service sshd start
