#!/bin/sh

# Reload fail2ban if installed
#------------------------------

if [ -x /usr/bin/fail2ban-server ]; then
    logger -p local6.notice -t installer "app-ssh-server-core - enabling Attack Detector configlet"
    service fail2ban condrestart >/dev/null 2>&1
fi
