<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ssh_server_allow_passwords'] = 'Zezwól na hasła';
$lang['ssh_server_allow_root_login'] = 'Zezwól na logowanie roota';
$lang['ssh_server_app_description'] = 'Aplikacja serwera SSH dostarcza narzędzi do zarządzania bezpieczną powłoką dla Twojego systemu.';
$lang['ssh_server_app_name'] = 'Serwer SSH';
$lang['ssh_server_app_tooltip'] = 'Modyfikacja ustawień zabezpieczeń serwera SSH może być wymagana do osiągnięcia zgodności z obowiązującymi przepisami takimi jak np. PCI lub w celu wymuszenie firmowej polityki standardów bezpieczeństwa.';
$lang['ssh_server_password_authentication_policy_invalid'] = 'Reguła uwierzytelniania hasłem jest nieprawidłowa.';
$lang['ssh_server_permit_root_login_policy_invalid'] = 'Reguła logowania roota jest nieprawidłowa.';
